const makeConcept = ({
  id,
  order,
  title,
  question,
  core,
  intuition,
  formulas,
  example,
  mistake,
  check,
  practice,
}) => ({
  id,
  order,
  title,
  question,
  core,
  intuition,
  formulas,
  example: { prompt: example[0], steps: example[1], answer: example[2] },
  mistake,
  check: { prompt: check[0], answer: check[1], reason: check[2] },
  practice: practice.map(([prompt, answer, reason]) => ({ prompt, answer, reason })),
});

export const MATH1_SEQUENCE_CONCEPTS = [
  makeConcept({
    id: "math1-arithmetic-sequences", order: 1, title: "등차수열", question: "일정한 수만큼 늘거나 줄어드는 수열의 n번째 항은 어떻게 찾을까?",
    core: "이웃한 두 항의 차가 일정한 수열은 첫째항에 공차를 n-1번 더해 일반항을 구합니다.",
    intuition: "첫째항에서 둘째항까지 공차를 한 번, n번째 항까지는 n-1번 더합니다. 항의 번호와 더한 횟수가 하나 차이 난다는 점이 핵심입니다.",
    formulas: [String.raw`a_n=a_1+(n-1)d`, String.raw`a_n-a_{n-1}=d`],
    example: [String.raw`3,7,11,\ldots\text{의 }a_{10}`, [String.raw`a_1=3,\ d=4`, String.raw`a_{10}=3+9\cdot4=39`], String.raw`39`],
    mistake: "n번째 항까지 공차를 n번 더하지 않습니다. 첫째항에서 출발하므로 공차를 더하는 횟수는 n-1번입니다.",
    check: [String.raw`a_1=5,\ d=-2\text{일 때 }a_8`, String.raw`-9`, "5에 공차 -2를 일곱 번 더하면 5-14=-9입니다."],
    practice: [[String.raw`2,5,8,\ldots\text{의 }a_{20}`, String.raw`59`, "첫째항 2에 공차 3을 19번 더하면 59입니다."], [String.raw`a_4=10,\ a_9=25\text{일 때 }d`, String.raw`3`, "두 항의 차 15는 공차를 다섯 번 더한 값이므로 d=3입니다."]],
  }),
  makeConcept({
    id: "math1-geometric-sequences", order: 2, title: "등비수열", question: "앞 항에 일정한 수를 곱해 만드는 수열은 어떻게 표현할까?",
    core: "이웃한 항의 비가 일정한 수열은 첫째항에 공비를 n-1번 곱해 일반항을 구합니다.",
    intuition: "등차수열이 같은 양을 더하는 변화라면 등비수열은 같은 비율로 커지거나 작아지는 변화입니다. n번째 항에는 공비가 n-1개 들어갑니다.",
    formulas: [String.raw`a_n=a_1r^{n-1}`, String.raw`\frac{a_n}{a_{n-1}}=r`],
    example: [String.raw`2,6,18,\ldots\text{의 }a_6`, [String.raw`a_1=2,\ r=3`, String.raw`a_6=2\cdot3^5=486`], String.raw`486`],
    mistake: "공비가 음수이면 항의 부호가 번갈아 바뀝니다. 절댓값만 보고 공비를 양수로 정하지 않습니다.",
    check: [String.raw`a_1=81,\ r=\frac13\text{일 때 }a_5`, String.raw`1`, "81에 1/3을 네 번 곱하면 81/81=1입니다."],
    practice: [[String.raw`3,-6,12,\ldots\text{의 }a_7`, String.raw`192`, "공비가 -2이므로 a₇=3(-2)⁶=192입니다."], [String.raw`a_2=6,\ a_5=162,\ r>0\text{일 때 }r`, String.raw`3`, "a₅/a₂=r³=27이고 공비가 양수이므로 r=3입니다."]],
  }),
  makeConcept({
    id: "math1-sequence-sums", order: 3, title: "수열의 합과 시그마", question: "규칙이 있는 여러 항의 합을 빠르게 계산하려면 어떻게 할까?",
    core: "시그마는 일정한 규칙의 합을 짧게 쓰는 기호이며, 등차·등비수열의 합 공식은 첫째항과 마지막항 또는 공비로 계산합니다.",
    intuition: "등차수열은 앞뒤 항을 짝지으면 합이 같아지고, 등비수열은 전체 합에 공비를 곱한 뒤 원래 합을 빼면 중간 항이 사라집니다.",
    formulas: [String.raw`\sum_{k=1}^{n}k=\frac{n(n+1)}2`, String.raw`S_n=\frac n2(a_1+a_n)`, String.raw`S_n=a_1\frac{1-r^n}{1-r}\quad(r\ne1)`],
    example: [String.raw`2+5+8+\cdots+29`, [String.raw`29=2+(n-1)3\text{에서 }n=10`, String.raw`S_{10}=\frac{10}{2}(2+29)=155`], String.raw`155`],
    mistake: "등비수열의 합에서 분자와 분모의 부호를 섞지 않습니다. (1-rⁿ)/(1-r) 또는 (rⁿ-1)/(r-1) 중 하나를 일관되게 씁니다.",
    check: [String.raw`\sum_{k=1}^{10}(2k-1)`, String.raw`100`, "처음 열 개의 홀수의 합은 10²이므로 100입니다."],
    practice: [[String.raw`1+2+4+\cdots+32`, String.raw`63`, "첫째항 1, 공비 2, 여섯 항인 등비수열의 합은 2⁶-1=63입니다."], [String.raw`\sum_{k=1}^{5}(3k+1)`, String.raw`50`, "3(1+2+3+4+5)+5=45+5=50입니다."]],
  }),
  makeConcept({
    id: "math1-mathematical-induction", order: 4, title: "수학적 귀납법", question: "모든 자연수에 대해 성립하는 명제를 어떻게 증명할까?",
    core: "첫 자연수에서 성립함을 보이고, n=k에서 성립한다고 가정해 n=k+1에서도 성립함을 증명합니다.",
    intuition: "첫 도미노가 쓰러지고 하나가 쓰러질 때마다 다음 도미노도 쓰러진다면 모든 도미노가 쓰러집니다. 두 단계 가운데 하나라도 빠지면 모든 자연수에 대한 증명이 되지 않습니다.",
    formulas: [String.raw`P(1)\text{ 확인}`, String.raw`P(k)\Rightarrow P(k+1)`],
    example: [String.raw`\begin{gathered}1+3+\cdots+(2n-1)=n^2\\\text{귀납 단계 확인}\end{gathered}`, [String.raw`n=k\text{일 때 합이 }k^2\text{라 가정}`, String.raw`k^2+(2k+1)=(k+1)^2`], String.raw`P(k+1)\text{ 성립}`],
    mistake: "P(k)가 참이라고 가정한 것만으로 증명이 끝나지 않습니다. 그 가정을 실제로 사용해 P(k+1)을 만들어야 합니다.",
    check: [String.raw`1+2+\cdots+n=\frac{n(n+1)}2\text{에서 }P(k+1)\text{의 우변}`, String.raw`\frac{(k+1)(k+2)}2`, "식의 n 자리에 k+1을 넣으면 (k+1)(k+2)/2가 됩니다."],
    practice: [[String.raw`2+4+\cdots+2k=k(k+1)\text{일 때 다음에 더할 항}`, String.raw`2(k+1)`, "k번째 짝수 2k 다음의 짝수는 2(k+1)입니다."], [String.raw`1+2+\cdots+k=\frac{k(k+1)}2\text{일 때 }1+\cdots+(k+1)`, String.raw`\frac{(k+1)(k+2)}2`, "가정한 합에 k+1을 더하고 묶으면 (k+1)(k+2)/2입니다."]],
  }),
];

export const MATH2_LIMIT_CONTINUITY_CONCEPTS = [
  makeConcept({
    id: "math2-function-limits", order: 1, title: "함수의 극한", question: "x가 한 값에 가까워질 때 함수값은 어디에 가까워질까?",
    core: "함수의 극한은 x가 a와 같을 때의 값이 아니라 a에 한없이 가까워질 때 f(x)가 가까워지는 값을 말합니다.",
    intuition: "극한은 도착점의 사진이 아니라 그 점을 향해 가는 움직임을 보는 개념입니다. f(a)가 없어도 왼쪽과 오른쪽에서 같은 값으로 다가가면 극한은 존재합니다.",
    formulas: [String.raw`\lim_{x\to a}f(x)=L`, String.raw`\lim_{x\to a-}f(x)=\lim_{x\to a+}f(x)=L`],
    example: [String.raw`\lim_{x\to2}(3x-1)`, [String.raw`다항함수는 x=2를 직접 대입할 수 있습니다.`, String.raw`3\cdot2-1=5`], String.raw`5`],
    mistake: "왼쪽 극한과 오른쪽 극한이 다르면 함수값이 따로 존재해도 극한은 존재하지 않습니다.",
    check: [String.raw`\lim_{x\to-1}(x^2+2x)`, String.raw`-1`, "다항식에 x=-1을 대입하면 1-2=-1입니다."],
    practice: [[String.raw`\lim_{x\to3}(2x^2-x)`, String.raw`15`, "다항식에 3을 대입하면 18-3=15입니다."], [String.raw`\begin{gathered}\lim_{x\to1-}f(x)=2\\\lim_{x\to1+}f(x)=5\end{gathered}\text{일 때 }\lim_{x\to1}f(x)`, String.raw`\text{존재하지 않음}`, "좌극한과 우극한이 서로 다르므로 양쪽 극한은 존재하지 않습니다."]],
  }),
  makeConcept({
    id: "math2-limit-calculation", order: 2, title: "극한값의 계산", question: "직접 대입하면 0/0이 되는 극한은 어떻게 계산할까?",
    core: "분자와 분모를 인수분해해 0이 되는 공통인자를 약분한 뒤 극한값을 계산합니다.",
    intuition: "x=a에서는 원래 식이 정의되지 않더라도 a가 아닌 가까운 곳에서 같은 값을 갖는 간단한 식으로 바꿀 수 있습니다. 극한은 바로 그 주변의 값을 보기 때문에 약분이 가능합니다.",
    formulas: [String.raw`\lim(f\pm g)=\lim f\pm\lim g`, String.raw`\lim(fg)=(\lim f)(\lim g)`, String.raw`\lim\frac fg=\frac{\lim f}{\lim g}\quad(\lim g\ne0)`],
    example: [String.raw`\lim_{x\to2}\frac{x^2-4}{x-2}`, [String.raw`x^2-4=(x-2)(x+2)`, String.raw`x\ne2\text{에서 }x+2\text{이므로 극한은 }4`], String.raw`4`],
    mistake: "0/0은 답이 0이라는 뜻이 아니라 바로 계산할 수 없다는 신호입니다. 먼저 인수분해나 유리화를 시도합니다.",
    check: [String.raw`\lim_{x\to1}\frac{x^2-1}{x-1}`, String.raw`2`, "분자를 (x-1)(x+1)로 인수분해하고 약분하면 x+1의 극한은 2입니다."],
    practice: [[String.raw`\lim_{x\to3}\frac{x^2-9}{x-3}`, String.raw`6`, "공통인자 x-3을 약분하면 x+3이 남아 극한값은 6입니다."], [String.raw`\lim_{x\to0}\frac{(x+2)^2-4}{x}`, String.raw`4`, "분자를 x(x+4)로 정리하고 x를 약분하면 x+4의 극한은 4입니다."]],
  }),
  makeConcept({
    id: "math2-continuity", order: 3, title: "함수의 연속", question: "그래프가 한 점에서 끊기지 않으려면 무엇이 같아야 할까?",
    core: "x=a에서 연속이려면 f(a)가 정의되고 극한이 존재하며 그 극한값과 f(a)가 같아야 합니다.",
    intuition: "연속은 그래프를 그 점 근처에서 펜을 떼지 않고 지날 수 있다는 뜻입니다. 다가가는 높이와 실제 점의 높이가 정확히 만나야 합니다.",
    formulas: [String.raw`\lim_{x\to a}f(x)=f(a)`, String.raw`\lim_{x\to a-}f(x)=\lim_{x\to a+}f(x)=f(a)`],
    example: [String.raw`f(x)=\begin{cases}x+1&(x<2)\\k&(x=2)\\5-x&(x>2)\end{cases}\text{가 }x=2\text{에서 연속}`, [String.raw`좌극한은 3, 우극한도 3입니다.`, String.raw`f(2)=k=3\text{이어야 합니다.}`], String.raw`k=3`],
    mistake: "함수값만 존재하거나 좌우 극한만 같다고 연속은 아닙니다. 극한값과 실제 함수값까지 모두 같아야 합니다.",
    check: [String.raw`f(x)=\begin{cases}2x&(x<1)\\a&(x\ge1)\end{cases}\text{가 }x=1\text{에서 연속일 때 }a`, String.raw`2`, "왼쪽에서 다가간 값 2와 f(1)=a가 같아야 하므로 a=2입니다."],
    practice: [[String.raw`f(x)=\frac{x^2-4}{x-2}\ (x\ne2),\ f(2)=k\text{가 연속일 때 }k`, String.raw`4`, "약분한 x+2의 x→2 극한값 4와 함수값 k가 같아야 합니다."], [String.raw`f(x)=|x|\text{는 }x=0\text{에서 연속인가?}`, String.raw`\text{연속이다}`, "좌우에서 모두 0으로 다가가고 실제 함수값 f(0)도 0입니다."]],
  }),
  makeConcept({
    id: "math2-continuous-function-properties", order: 4, title: "연속함수의 성질", question: "연속인 함수는 구간 안에서 어떤 값을 반드시 지나갈까?",
    core: "닫힌구간에서 연속인 함수는 최댓값과 최솟값을 가지며, 양 끝 함수값 사이의 모든 값을 적어도 한 번 갖습니다.",
    intuition: "끊어지지 않은 그래프가 한 높이에서 다른 높이로 이동하려면 그 사이 높이를 건너뛸 수 없습니다. 이 성질로 방정식의 해가 구간 안에 있음을 보일 수 있습니다.",
    formulas: [String.raw`\begin{gathered}f(a)f(b)<0\\\Rightarrow \exists c\in(a,b):f(c)=0\end{gathered}`, String.raw`m\le f(x)\le M\quad(a\le x\le b)`],
    example: [String.raw`\begin{gathered}f(x)=x^3+x-1\\(0,1)\text{에서 근을 가짐을 확인}\end{gathered}`, [String.raw`f(0)=-1,\ f(1)=1`, String.raw`연속이고 부호가 바뀌므로 중간값 정리에 의해 근이 있습니다.`], String.raw`(0,1)\text{에 적어도 한 근}`],
    mistake: "양 끝 함수값의 부호가 같다고 근이 없다고 단정할 수 없습니다. 부호가 다르면 존재가 보장된다는 충분조건입니다.",
    check: [String.raw`f(x)=x^2-2\text{가 근을 갖는 구간}`, String.raw`(1,2)`, "f(1)=-1, f(2)=2이고 다항함수는 연속이므로 (1,2)에 근이 있습니다."],
    practice: [[String.raw`f(x)=x^3-5\text{가 근을 갖는 정수 끝점 구간}`, String.raw`(1,2)`, "f(1)=-4와 f(2)=3의 부호가 달라 그 사이에 근이 존재합니다."], [String.raw`[0,2]\text{에서 연속인 }f,\ f(0)=1,\ f(2)=4\text{일 때 반드시 갖는 값 하나}`, String.raw`3`, "중간값 정리에 의해 1과 4 사이의 값 3을 적어도 한 번 갖습니다."]],
  }),
];

export const MATH2_DIFFERENTIATION_CONCEPTS = [
  makeConcept({
    id: "math2-derivative-definition", order: 1, title: "미분계수와 도함수", question: "한 점에서 순간적인 변화율은 어떻게 구할까?",
    core: "미분계수는 평균변화율의 극한이며, 각 x에서의 미분계수를 함수로 나타낸 것이 도함수입니다.",
    intuition: "두 점을 잇는 할선의 기울기에서 두 점 사이를 한없이 좁히면 한 점에서의 접선 기울기가 됩니다. 이것이 순간변화율입니다.",
    formulas: [String.raw`f'(a)=\lim_{h\to0}\frac{f(a+h)-f(a)}h`, String.raw`f'(x)=\lim_{h\to0}\frac{f(x+h)-f(x)}h`],
    example: [String.raw`f(x)=x^2\text{일 때 }f'(2)`, [String.raw`\frac{(2+h)^2-4}{h}=4+h`, String.raw`h\to0\text{이면 }4`], String.raw`4`],
    mistake: "미분계수의 정의에서 분자는 반드시 함수값의 변화량이고 분모는 x의 변화량입니다. 순서를 서로 맞춰야 합니다.",
    check: [String.raw`f(x)=3x+1\text{일 때 }f'(4)`, String.raw`3`, "일차함수의 변화율은 모든 점에서 직선의 기울기 3으로 같습니다."],
    practice: [[String.raw`f(x)=x^2+1\text{일 때 }f'(1)`, String.raw`2`, "정의식의 분자를 전개하고 h를 약분하면 2+h가 되어 극한은 2입니다."], [String.raw`\lim_{h\to0}\frac{f(3+h)-f(3)}h\text{이 나타내는 값}`, String.raw`f'(3)`, "x=3에서 함수 f의 미분계수를 정의 그대로 나타낸 식입니다."]],
  }),
  makeConcept({
    id: "math2-polynomial-derivatives", order: 2, title: "다항함수의 미분", question: "다항식을 빠르게 미분하는 규칙은 무엇일까?",
    core: "x의 n제곱은 nx의 n-1제곱으로 미분하고, 각 항을 따로 미분한 뒤 더합니다.",
    intuition: "거듭제곱을 미분하면 지수가 앞으로 내려오고 지수는 하나 줄어듭니다. 상수항은 x가 변해도 그대로이므로 변화율이 0입니다.",
    formulas: [String.raw`(x^n)'=nx^{n-1}`, String.raw`(af+bg)'=af'+bg'`, String.raw`C'=0`],
    example: [String.raw`f(x)=2x^3-5x^2+4`, [String.raw`(2x^3)'=6x^2,\ (-5x^2)'=-10x`, String.raw`f'(x)=6x^2-10x`], String.raw`6x^2-10x`],
    mistake: "항을 미분할 때 계수를 없애거나 지수만 하나 줄이지 않습니다. 기존 계수에 원래 지수를 곱합니다.",
    check: [String.raw`(x^4-3x+7)'`, String.raw`4x^3-3`, "x⁴은 4x³, -3x는 -3, 상수 7은 0으로 미분됩니다."],
    practice: [[String.raw`(5x^3+2x^2-x)'`, String.raw`15x^2+4x-1`, "각 항에 거듭제곱 미분법을 적용해 차례로 더합니다."], [String.raw`f(x)=x^3-6x^2\text{일 때 }f'(2)`, String.raw`-12`, "f'(x)=3x²-12x에 x=2를 넣으면 12-24=-12입니다."]],
  }),
  makeConcept({
    id: "math2-tangent-mean-value", order: 3, title: "접선과 평균값 정리", question: "한 점의 접선 기울기와 구간의 평균 기울기는 어떻게 연결될까?",
    core: "접선의 기울기는 그 점의 미분계수이며, 연속·미분 가능한 함수에는 평균변화율과 같은 순간변화율을 갖는 점이 있습니다.",
    intuition: "구간 전체를 이동한 평균 경사와 정확히 평행한 접선이 구간 안 어딘가에 존재합니다. 접선 문제는 점의 좌표와 기울기를 먼저 찾으면 됩니다.",
    formulas: [String.raw`y-f(a)=f'(a)(x-a)`, String.raw`f'(c)=\frac{f(b)-f(a)}{b-a}`],
    example: [String.raw`y=x^2\text{의 }x=1\text{에서 접선}`, [String.raw`f(1)=1,\ f'(1)=2`, String.raw`y-1=2(x-1)`], String.raw`y=2x-1`],
    mistake: "접선식에 기울기만 넣고 접점 좌표를 빼먹지 않습니다. y-y₁=m(x-x₁)의 꼴로 씁니다.",
    check: [String.raw`f(x)=x^2\text{에서 }[0,2]\text{의 평균값 정리의 }c`, String.raw`1`, "평균변화율은 2이고 f'(c)=2c=2이므로 c=1입니다."],
    practice: [[String.raw`y=x^3\text{의 }x=1\text{에서 접선}`, String.raw`y=3x-2`, "접점 (1,1)과 기울기 f'(1)=3을 접선식에 넣습니다."], [String.raw`f(x)=x^2+x\text{에서 }[1,3]\text{의 평균변화율}`, String.raw`5`, "(f(3)-f(1))/(3-1)=(12-2)/2=5입니다."]],
  }),
  makeConcept({
    id: "math2-derivative-applications", order: 4, title: "함수의 증가·감소와 극값", question: "도함수의 부호로 그래프의 모양을 어떻게 판단할까?",
    core: "f'(x)>0이면 증가하고 f'(x)<0이면 감소하며, 도함수의 부호가 바뀌는 점에서 극대 또는 극소가 생깁니다.",
    intuition: "도함수는 그래프가 향하는 방향을 나타냅니다. 양수면 오른쪽으로 갈수록 올라가고 음수면 내려갑니다. 0인 점의 앞뒤 부호를 반드시 비교해야 합니다.",
    formulas: [String.raw`f'(x)>0\Rightarrow f\text{ 증가}`, String.raw`f'(x)<0\Rightarrow f\text{ 감소}`, String.raw`+\to-:\text{ 극대},\quad-\to+:\text{ 극소}`],
    example: [String.raw`f(x)=x^3-3x\text{의 극값}`, [String.raw`f'(x)=3(x-1)(x+1)`, String.raw`x=-1\text{에서 }+\to-,\ x=1\text{에서 }-\to+`, String.raw`f(-1)=2,\ f(1)=-2`], String.raw`\text{극댓값 }2,\ \text{극솟값 }-2`],
    mistake: "f'(a)=0이라는 사실만으로 극값이라 하지 않습니다. 앞뒤에서 도함수의 부호가 실제로 바뀌는지 확인합니다.",
    check: [String.raw`f(x)=x^2-4x+1\text{의 최솟값}`, String.raw`-3`, "f'(x)=2x-4가 x=2에서 음수에서 양수로 바뀌고 f(2)=-3입니다."],
    practice: [[String.raw`f(x)=-x^2+6x\text{의 최댓값}`, String.raw`9`, "f'(x)=-2x+6이 x=3에서 양수에서 음수로 바뀌며 f(3)=9입니다."], [String.raw`f'(x)=(x-2)(x+1)\text{일 때 극소가 되는 }x`, String.raw`2`, "도함수 부호가 x=2에서 음수에서 양수로 바뀌므로 극소점입니다."]],
  }),
];

export const MATH2_INTEGRATION_CONCEPTS = [
  makeConcept({
    id: "math2-indefinite-integrals", order: 1, title: "부정적분", question: "미분하면 주어진 함수가 되는 모든 함수는 어떻게 찾을까?",
    core: "부정적분은 미분의 역연산이며, 같은 도함수를 갖는 함수들은 상수만큼 차이 나므로 적분상수 C를 붙입니다.",
    intuition: "기울기 정보만으로 원래 그래프의 세로 위치까지 정할 수 없습니다. 위아래로 평행이동한 모든 그래프가 같은 도함수를 가지므로 임의의 상수 C가 필요합니다.",
    formulas: [String.raw`\int x^n\,dx=\frac{x^{n+1}}{n+1}+C\quad(n\ne-1)`, String.raw`\int(af+bg)dx=a\int fdx+b\int gdx`],
    example: [String.raw`\int(3x^2-4x+1)\,dx`, [String.raw`\int3x^2dx=x^3,\ \int-4x\,dx=-2x^2`, String.raw`x^3-2x^2+x+C`], String.raw`x^3-2x^2+x+C`],
    mistake: "부정적분에는 적분상수 C를 빠뜨리지 않습니다. 각 항마다 붙이지 않고 식 전체에 하나를 붙이면 됩니다.",
    check: [String.raw`\int(2x+3)\,dx`, String.raw`x^2+3x+C`, "각 항의 지수를 하나 올리고 새 지수로 나눈 뒤 적분상수를 붙입니다."],
    practice: [[String.raw`\int(4x^3-2)\,dx`, String.raw`x^4-2x+C`, "4x³의 원시함수는 x⁴이고 상수 -2의 원시함수는 -2x입니다."], [String.raw`F'(x)=6x,\ F(1)=4\text{일 때 }F(x)`, String.raw`3x^2+1`, "F=3x²+C에 F(1)=4를 넣으면 C=1입니다."]],
  }),
  makeConcept({
    id: "math2-definite-integrals", order: 2, title: "정적분", question: "구간에서 변화가 누적된 양은 어떻게 계산할까?",
    core: "정적분은 한 원시함수 F를 찾아 윗끝 값에서 아랫끝 값을 뺀 F(b)-F(a)로 계산합니다.",
    intuition: "정적분은 작은 변화량을 구간 전체에 걸쳐 쌓은 값입니다. 적분상수는 두 끝에서 빼는 과정에서 사라지므로 쓰지 않습니다.",
    formulas: [String.raw`\int_a^b f(x)dx=F(b)-F(a)`, String.raw`\int_a^b f=-\int_b^a f`, String.raw`\int_a^b f+\int_b^c f=\int_a^c f`],
    example: [String.raw`\int_0^2(2x+1)\,dx`, [String.raw`F(x)=x^2+x`, String.raw`F(2)-F(0)=6`], String.raw`6`],
    mistake: "정적분에서 아랫끝과 윗끝의 순서를 바꾸면 부호가 바뀝니다. 항상 F(윗끝)-F(아랫끝) 순서로 계산합니다.",
    check: [String.raw`\int_1^3 x\,dx`, String.raw`4`, "x²/2에 3과 1을 넣어 빼면 (9-1)/2=4입니다."],
    practice: [[String.raw`\int_{-1}^{1}x^2\,dx`, String.raw`\frac23`, "x³/3의 1에서 값과 -1에서 값을 빼면 1/3-(-1/3)=2/3입니다."], [String.raw`\int_0^1 3x^2\,dx`, String.raw`1`, "원시함수 x³을 0과 1에 대입해 빼면 1입니다."]],
  }),
  makeConcept({
    id: "math2-area-integrals", order: 3, title: "정적분과 넓이", question: "그래프와 x축 또는 두 그래프 사이의 넓이는 어떻게 구할까?",
    core: "넓이는 위 함수에서 아래 함수를 뺀 값을 적분하며, x축을 지날 때는 부호가 바뀌는 점에서 구간을 나눕니다.",
    intuition: "정적분은 x축 아래 부분을 음수로 세지만 넓이는 항상 양수입니다. 따라서 어느 그래프가 위에 있는지 확인하고 교점에서 구간을 나눠야 합니다.",
    formulas: [String.raw`A=\int_a^b|f(x)|dx`, String.raw`A=\int_a^b\{f(x)-g(x)\}dx\quad(f\ge g)`],
    example: [String.raw`y=x\text{와 x축, }0\le x\le2\text{의 넓이}`, [String.raw`0\le x\le2\text{에서 }x\ge0`, String.raw`\int_0^2x\,dx=2`], String.raw`2`],
    mistake: "정적분값이 음수라고 넓이도 음수인 것은 아닙니다. 그래프가 x축 아래에 있으면 부호를 바꾸어 넓이를 구합니다.",
    check: [String.raw`y=x^2\text{와 }y=x\text{ 사이 }0\le x\le1\text{의 넓이}`, String.raw`\frac16`, "구간에서 x가 x²보다 위이므로 ∫₀¹(x-x²)dx=1/2-1/3=1/6입니다."],
    practice: [[String.raw`y=2-x\text{와 x축, }0\le x\le2\text{의 넓이}`, String.raw`2`, "밑변과 높이가 모두 2인 삼각형이므로 넓이는 2이며 적분값도 같습니다."], [String.raw`y=x^2-1\text{과 x축, }-1\le x\le1\text{의 넓이}`, String.raw`\frac43`, "구간 안에서 함수가 0 이하이므로 ∫₋₁¹(1-x²)dx=4/3입니다."]],
  }),
  makeConcept({
    id: "math2-motion-integrals", order: 4, title: "속도와 거리", question: "위치·속도·가속도와 실제 이동 거리는 어떻게 연결될까?",
    core: "위치를 미분하면 속도, 속도를 미분하면 가속도이며, 이동 거리는 속도의 절댓값을 적분합니다.",
    intuition: "변위는 출발점과 도착점만 비교하지만 이동 거리는 되돌아간 길이까지 모두 셉니다. 속도의 부호가 바뀌는 시각에서 구간을 나누는 이유입니다.",
    formulas: [String.raw`v(t)=s'(t),\quad a(t)=v'(t)`, String.raw`\text{변위}=\int_a^b v(t)dt`, String.raw`\text{거리}=\int_a^b|v(t)|dt`],
    example: [String.raw`\begin{gathered}v(t)=2t-2\quad(0\le t\le2)\\\text{이 구간의 이동 거리}\end{gathered}`, [String.raw`v(t)=0\text{인 시각은 }t=1`, String.raw`\int_0^1(2-2t)dt+\int_1^2(2t-2)dt=2`], String.raw`2`],
    mistake: "속도의 정적분은 변위입니다. 속도가 음수가 되는 구간이 있으면 실제 이동 거리는 절댓값을 적분해야 합니다.",
    check: [String.raw`s(t)=t^3-3t\text{일 때 }t=1\text{의 속도}`, String.raw`0`, "s'(t)=3t²-3이므로 t=1에서 속도는 0입니다."],
    practice: [[String.raw`s(t)=t^2+2t\text{일 때 }t=2\text{의 가속도}`, String.raw`2`, "속도는 2t+2이고 이를 다시 미분한 가속도는 항상 2입니다."], [String.raw`v(t)=3\ (0\le t\le4)\text{의 이동 거리}`, String.raw`12`, "속도가 항상 양수이므로 3을 0부터 4까지 적분하면 12입니다."]],
  }),
];

export const MATH2_CONCEPTS_BY_UNIT = {
  "math2-limits-continuity": MATH2_LIMIT_CONTINUITY_CONCEPTS,
  "math2-differentiation": MATH2_DIFFERENTIATION_CONCEPTS,
  "math2-integration": MATH2_INTEGRATION_CONCEPTS,
};

export const PROBABILITY_COUNTING_CONCEPTS = [
  makeConcept({
    id: "probability-permutations", order: 1, title: "순열", question: "서로 다른 대상을 순서 있게 나열하는 경우는 몇 가지일까?",
    core: "서로 다른 n개에서 r개를 골라 순서 있게 나열하는 경우의 수는 nPr입니다.",
    intuition: "첫 자리는 n가지, 다음 자리는 남은 n-1가지처럼 선택지가 하나씩 줄어듭니다. 순서가 바뀌면 다른 결과로 세는지가 순열과 조합을 가르는 기준입니다.",
    formulas: [String.raw`{}_nP_r=n(n-1)\cdots(n-r+1)=\frac{n!}{(n-r)!}`, String.raw`n!=n(n-1)\cdots1`],
    example: [String.raw`5\text{명 중 회장과 부회장 뽑기}`, [String.raw`회장은 5가지, 부회장은 남은 4가지`, String.raw`{}_5P_2=5\cdot4=20`], String.raw`20`],
    mistake: "역할이나 자리의 순서가 다르면 다른 경우입니다. 회장 A·부회장 B와 회장 B·부회장 A를 하나로 세지 않습니다.",
    check: [String.raw`6\text{명 중 3명을 한 줄로 세우는 경우의 수}`, String.raw`120`, "6P3=6×5×4이므로 모두 120가지입니다."],
    practice: [[String.raw`7\text{개 중 2개를 순서 있게 고르는 경우의 수}`, String.raw`42`, "첫 선택 7가지와 다음 선택 6가지를 곱하면 42입니다."], [String.raw`4\text{명을 모두 한 줄로 세우는 경우의 수}`, String.raw`24`, "서로 다른 4명을 모두 나열하는 경우는 4!=24입니다."]],
  }),
  makeConcept({
    id: "probability-combinations", order: 2, title: "조합", question: "순서를 구별하지 않고 일부를 고르는 경우는 몇 가지일까?",
    core: "서로 다른 n개에서 순서 없이 r개를 고르는 경우의 수는 nCr이며, 순열을 r!로 나눈 값입니다.",
    intuition: "같은 r명을 뽑아도 줄 세우는 순서는 r!가지입니다. 조합에서는 이 순서들을 모두 같은 한 묶음으로 보기 때문에 순열을 r!로 나눕니다.",
    formulas: [String.raw`{}_nC_r=\frac{{}_nP_r}{r!}=\frac{n!}{r!(n-r)!}`, String.raw`{}_nC_r={}_nC_{n-r}`],
    example: [String.raw`6\text{명 중 대표 2명 고르기}`, [String.raw`순서를 구별하지 않으므로 조합입니다.`, String.raw`{}_6C_2=\frac{6\cdot5}{2}=15`], String.raw`15`],
    mistake: "뽑힌 사람의 역할이 모두 같으면 순서를 세지 않습니다. 문제에서 자리나 역할이 있는지 먼저 확인합니다.",
    check: [String.raw`8\text{명 중 3명으로 위원회 만들기}`, String.raw`56`, "순서 없는 선택이므로 8C3=8×7×6/(3×2×1)=56입니다."],
    practice: [[String.raw`10\text{개 중 2개 고르기}`, String.raw`45`, "10C2=10×9/2=45입니다."], [String.raw`9\text{명 중 7명 고르기}`, String.raw`36`, "9C7=9C2이고 9×8/2=36입니다."]],
  }),
  makeConcept({
    id: "probability-multiset-arrangements", order: 3, title: "같은 것이 있는 순열", question: "같은 문자가 섞인 배열은 중복을 어떻게 빼야 할까?",
    core: "전체 n개 가운데 같은 것이 각각 p개, q개라면 n!을 p!q! 등으로 나누어 중복 배열을 제거합니다.",
    intuition: "같은 문자끼리 자리를 바꿔도 눈에 보이는 배열은 달라지지 않습니다. 전체를 서로 다르다고 센 뒤, 보이지 않는 자리 바꿈의 수만큼 나눕니다.",
    formulas: [String.raw`\frac{n!}{p!q!\cdots}\quad(p+q+\cdots=n)`, String.raw`\frac{n!}{n_1!n_2!\cdots n_k!}`],
    example: [String.raw`A,A,B,B,C\text{를 나열하는 경우의 수}`, [String.raw`전체 5!에서 A의 교환 2!, B의 교환 2!를 나눕니다.`, String.raw`\frac{5!}{2!2!}=30`], String.raw`30`],
    mistake: "같은 종류의 개수만큼 나누는 것이 아니라 그 개수의 계승으로 나눕니다. A가 3개면 3이 아니라 3!입니다.",
    check: [String.raw`M,A,T,H,H\text{를 나열하는 경우의 수}`, String.raw`60`, "다섯 자리 전체 5!에서 같은 H 두 개의 교환 2!를 나누면 60입니다."],
    practice: [[String.raw`1,1,1,2,2\text{를 나열하는 경우의 수}`, String.raw`10`, "5!을 같은 1 세 개의 3!과 같은 2 두 개의 2!로 나누면 10입니다."], [String.raw`A,A,A,B,C,C\text{를 나열하는 경우의 수}`, String.raw`60`, "6!/(3!2!)=720/12=60입니다."]],
  }),
  makeConcept({
    id: "probability-binomial-theorem", order: 4, title: "이항정리", question: "(a+b)의 높은 거듭제곱에서 특정 항의 계수는 어떻게 찾을까?",
    core: "(a+b)^n의 전개에서 a^(n-r)b^r의 계수는 nCr이며, 조합의 수가 이항계수가 됩니다.",
    intuition: "n개의 괄호에서 b를 r번 선택하고 나머지에서 a를 선택하는 방법이 nCr가지라서 같은 항들이 그만큼 모입니다.",
    formulas: [String.raw`(a+b)^n=\sum_{r=0}^{n}{}_nC_r a^{n-r}b^r`, String.raw`{}_nC_0+{}_nC_1+\cdots+{}_nC_n=2^n`],
    example: [String.raw`(x+2)^4\text{에서 }x^2\text{의 계수}`, [String.raw`\text{일반항은 }{}_4C_r x^{4-r}2^r`, String.raw`4-r=2\text{이므로 }r=2,\ {}_4C_2\cdot2^2=24`], String.raw`24`],
    mistake: "x의 지수만 맞추고 상수의 거듭제곱을 빼먹지 않습니다. 일반항을 먼저 쓴 뒤 원하는 지수를 대입합니다.",
    check: [String.raw`(1+x)^5\text{에서 }x^3\text{의 계수}`, String.raw`10`, "x³을 고를 괄호 세 개를 정하는 방법이 5C3=10가지입니다."],
    practice: [[String.raw`(2+x)^4\text{에서 }x\text{의 계수}`, String.raw`32`, "x를 한 번 고르므로 4C1×2³=4×8=32입니다."], [String.raw`(a+b)^6\text{의 모든 계수의 합}`, String.raw`64`, "a=b=1을 대입하면 계수의 합은 (1+1)⁶=64입니다."]],
  }),
];

export const PROBABILITY_PROBABILITY_CONCEPTS = [
  makeConcept({
    id: "probability-basic-addition", order: 1, title: "확률과 덧셈정리", question: "여러 사건 중 하나가 일어날 확률은 어떻게 합칠까?",
    core: "모든 결과가 같은 가능성을 가지면 확률은 유리한 경우의 수를 전체 경우의 수로 나누며, 두 사건의 합에서는 겹치는 부분을 한 번 뺍니다.",
    intuition: "A의 확률과 B의 확률을 더하면 두 사건이 함께 일어난 부분을 두 번 세게 됩니다. 벤다이어그램의 겹친 부분을 한 번 빼는 이유입니다.",
    formulas: [String.raw`P(A)=\frac{n(A)}{n(S)}`, String.raw`P(A\cup B)=P(A)+P(B)-P(A\cap B)`, String.raw`P(A^c)=1-P(A)`],
    example: [String.raw`P(A)=\frac12,\ P(B)=\frac13,\ P(A\cap B)=\frac16\text{일 때 }P(A\cup B)`, [String.raw`덧셈정리에 값을 넣습니다.`, String.raw`\frac12+\frac13-\frac16=\frac23`], String.raw`\frac23`],
    mistake: "서로 배반인 사건에서만 교집합 확률이 0입니다. 겹칠 수 있는 두 사건의 확률을 무조건 더하지 않습니다.",
    check: [String.raw`P(A)=0.4\text{일 때 }P(A^c)`, String.raw`0.6`, "여사건의 확률은 전체 1에서 사건 A의 확률 0.4를 뺀 0.6입니다."],
    practice: [[String.raw`\text{주사위 한 개에서 짝수가 나올 확률}`, String.raw`\frac12`, "전체 여섯 결과 중 짝수는 2,4,6의 세 가지이므로 3/6입니다."], [String.raw`P(A)=0.5,\ P(B)=0.6,\ P(A\cap B)=0.3\text{일 때 }P(A\cup B)`, String.raw`0.8`, "두 확률의 합 1.1에서 겹친 확률 0.3을 빼면 0.8입니다."]],
  }),
  makeConcept({
    id: "probability-conditional", order: 2, title: "조건부확률", question: "어떤 사건이 이미 일어났을 때 확률은 어떻게 달라질까?",
    core: "B가 일어났다는 조건 아래 A의 확률은 표본공간을 B로 좁힌 뒤 A와 B의 교집합 비율을 계산합니다.",
    intuition: "조건이 주어지면 가능한 전체 결과가 달라집니다. 원래 전체가 아니라 B 안에서만 다시 유리한 결과와 전체 결과를 세는 것입니다.",
    formulas: [String.raw`P(A\mid B)=\frac{P(A\cap B)}{P(B)}\quad(P(B)>0)`, String.raw`P(A\cap B)=P(B)P(A\mid B)`],
    example: [String.raw`P(A\cap B)=0.2,\ P(B)=0.5\text{일 때 }P(A\mid B)`, [String.raw`조건부확률의 분모는 조건 사건 B입니다.`, String.raw`0.2\div0.5=0.4`], String.raw`0.4`],
    mistake: "P(A|B)와 P(B|A)는 일반적으로 다릅니다. 세로줄 오른쪽 사건이 분모가 되는 조건입니다.",
    check: [String.raw`P(A\cap B)=\frac16,\ P(B)=\frac12\text{일 때 }P(A\mid B)`, String.raw`\frac13`, "교집합 확률 1/6을 조건 사건의 확률 1/2로 나누면 1/3입니다."],
    practice: [[String.raw`P(B)=0.4,\ P(A\mid B)=0.5\text{일 때 }P(A\cap B)`, String.raw`0.2`, "곱셈정리에 따라 0.4×0.5=0.2입니다."], [String.raw`\text{카드 1~10 중 짝수라는 조건에서 4의 배수일 확률}`, String.raw`\frac25`, "짝수 2,4,6,8,10 다섯 개 중 4의 배수는 4와 8 두 개입니다."]],
  }),
  makeConcept({
    id: "probability-independence", order: 3, title: "사건의 독립", question: "한 사건의 발생이 다른 사건의 확률을 바꾸지 않는다는 것은 무슨 뜻일까?",
    core: "두 사건이 독립이면 한 사건을 조건으로 해도 다른 사건의 확률이 같고, 교집합 확률은 두 확률의 곱입니다.",
    intuition: "독립은 서로 영향을 주지 않는다는 뜻이고, 배반은 동시에 일어날 수 없다는 뜻입니다. 확률이 양수인 배반사건은 오히려 독립이 아닙니다.",
    formulas: [String.raw`P(A\cap B)=P(A)P(B)`, String.raw`P(A\mid B)=P(A)`],
    example: [String.raw`P(A)=\frac12,\ P(B)=\frac35\text{이고 독립일 때 }P(A\cap B)`, [String.raw`독립사건의 교집합은 곱합니다.`, String.raw`\frac12\cdot\frac35=\frac3{10}`], String.raw`\frac3{10}`],
    mistake: "독립과 배반을 같은 말로 보지 않습니다. 독립사건은 함께 일어날 수 있지만 서로의 확률을 바꾸지 않습니다.",
    check: [String.raw`P(A)=0.4,\ P(B)=0.5,\ P(A\cap B)=0.2\text{이면 독립인가?}`, String.raw`\text{독립이다}`, "P(A)P(B)=0.4×0.5=0.2로 교집합 확률과 같으므로 독립입니다."],
    practice: [[String.raw`\text{독립인 }A,B\text{에 대해 }P(A)=0.3,\ P(B)=0.2\text{일 때 둘 다 일어나지 않을 확률}`, String.raw`0.56`, "여사건도 독립이므로 0.7×0.8=0.56입니다."], [String.raw`P(A)=\frac12,\ P(B)=\frac14\text{인 배반사건은 독립인가?}`, String.raw`\text{독립이 아니다}`, "배반이면 교집합은 0이지만 확률의 곱은 1/8이어서 같지 않습니다."]],
  }),
  makeConcept({
    id: "probability-independent-trials", order: 4, title: "독립시행", question: "같은 실험을 반복할 때 성공 횟수의 확률은 어떻게 구할까?",
    core: "성공확률 p인 독립시행을 n번 하여 정확히 r번 성공할 확률은 성공 위치를 고르는 조합과 각 결과의 확률을 곱합니다.",
    intuition: "특정한 순서로 r번 성공할 확률은 p^r(1-p)^(n-r)이고, 성공이 놓일 r개의 자리를 고르는 방법이 nCr가지입니다.",
    formulas: [String.raw`P(X=r)={}_nC_rp^r(1-p)^{n-r}`],
    example: [String.raw`\begin{gathered}\text{동전 던지기 4회}\\\text{앞면이 2번 나올 확률}\end{gathered}`, [String.raw`\text{성공 위치는 }{}_4C_2\text{가지}`, String.raw`{}_4C_2(\frac12)^2(\frac12)^2=\frac38`], String.raw`\frac38`],
    mistake: "한 가지 순서의 확률만 계산하고 끝내지 않습니다. 성공이 나올 자리의 수 nCr를 반드시 곱합니다.",
    check: [String.raw`\text{성공확률 }\frac13\text{인 시행을 3번 해 모두 성공할 확률}`, String.raw`\frac1{27}`, "세 번 모두 성공하는 한 가지 경우이므로 (1/3)³=1/27입니다."],
    practice: [[String.raw`\text{성공확률 }\frac12\text{인 시행을 3번 해 정확히 1번 성공할 확률}`, String.raw`\frac38`, "성공 자리 3C1에 (1/2)¹(1/2)²를 곱하면 3/8입니다."], [String.raw`\text{성공확률 }0.2\text{인 시행을 2번 해 적어도 한 번 성공할 확률}`, String.raw`0.36`, "한 번도 성공하지 않을 확률 0.8²=0.64를 1에서 빼면 0.36입니다."]],
  }),
];

export const PROBABILITY_STATISTICS_CONCEPTS = [
  makeConcept({
    id: "statistics-random-variables", order: 1, title: "확률변수와 확률분포", question: "확률실험의 결과를 숫자로 나타내면 평균과 퍼짐을 어떻게 구할까?",
    core: "확률변수의 각 값과 그 확률을 곱해 더하면 평균이고, 평균에서 떨어진 거리의 제곱을 확률로 가중하면 분산입니다.",
    intuition: "기댓값은 실험을 매우 많이 반복했을 때의 장기 평균입니다. 분산은 값들이 평균 주변에 얼마나 퍼져 있는지를 제곱거리로 잽니다.",
    formulas: [String.raw`E(X)=\sum x_i p_i`, String.raw`V(X)=E(X^2)-\{E(X)\}^2`, String.raw`\sigma(X)=\sqrt{V(X)}`],
    example: [String.raw`P(X=0)=\frac12,\ P(X=2)=\frac12\text{일 때 }E(X)`, [String.raw`각 값에 그 확률을 곱합니다.`, String.raw`0\cdot\frac12+2\cdot\frac12=1`], String.raw`1`],
    mistake: "확률의 합은 반드시 1인지 먼저 확인합니다. 평균을 구할 때 확률을 빼고 값만 더해 나누지 않습니다.",
    check: [String.raw`P(X=1)=\frac14,\ P(X=3)=\frac34\text{일 때 }E(X)`, String.raw`\frac52`, "1×1/4+3×3/4=1/4+9/4=5/2입니다."],
    practice: [[String.raw`P(X=-1)=P(X=1)=\frac12\text{일 때 }V(X)`, String.raw`1`, "평균은 0이고 X²의 평균은 1이므로 분산은 1입니다."], [String.raw`E(X)=2,\ E(X^2)=7\text{일 때 }V(X)`, String.raw`3`, "V(X)=E(X²)-{E(X)}²=7-4=3입니다."]],
  }),
  makeConcept({
    id: "statistics-binomial-distribution", order: 2, title: "이항분포", question: "독립시행의 성공 횟수는 어떤 평균과 분산을 가질까?",
    core: "성공확률 p인 시행을 n번 반복한 성공 횟수 X는 이항분포 B(n,p)를 따르며 평균 np, 분산 np(1-p)입니다.",
    intuition: "각 시행의 성공 여부를 0 또는 1로 보면 성공 횟수는 이 값들의 합입니다. 한 번의 평균 p와 분산 p(1-p)가 n번 쌓입니다.",
    formulas: [String.raw`X\sim B(n,p)`, String.raw`E(X)=np`, String.raw`V(X)=np(1-p)`],
    example: [String.raw`X\sim B(10,0.3)\text{일 때 평균과 분산}`, [String.raw`E(X)=10\cdot0.3=3`, String.raw`V(X)=10\cdot0.3\cdot0.7=2.1`], String.raw`E(X)=3,\ V(X)=2.1`],
    mistake: "이항분포의 분산을 np²로 계산하지 않습니다. 실패확률 1-p까지 곱해야 합니다.",
    check: [String.raw`X\sim B(20,\frac12)\text{일 때 }E(X)`, String.raw`10`, "이항분포의 평균은 np이므로 20×1/2=10입니다."],
    practice: [[String.raw`X\sim B(8,\frac14)\text{일 때 }V(X)`, String.raw`\frac32`, "np(1-p)=8×1/4×3/4=3/2입니다."], [String.raw`X\sim B(5,0.2)\text{일 때 }P(X=0)`, String.raw`0.8^5`, "성공이 한 번도 없으려면 다섯 시행이 모두 실패해야 하므로 0.8⁵입니다."]],
  }),
  makeConcept({
    id: "statistics-normal-distribution", order: 3, title: "정규분포", question: "평균 주변에 종 모양으로 모이는 자료의 확률은 어떻게 구할까?",
    core: "정규분포는 평균을 중심으로 대칭이며, 표준화하면 평균 0·표준편차 1인 표준정규분포의 확률로 바꿀 수 있습니다.",
    intuition: "서로 다른 평균과 퍼짐을 가진 정규분포도 평균에서 몇 표준편차 떨어졌는지로 바꾸면 같은 표를 사용할 수 있습니다.",
    formulas: [String.raw`X\sim N(m,\sigma^2)`, String.raw`Z=\frac{X-m}{\sigma}\sim N(0,1)`, String.raw`P(X\le m)=\frac12`],
    example: [String.raw`X\sim N(100,15^2)\text{에서 }X=130\text{의 표준화 값}`, [String.raw`평균과의 차는 130-100=30`, String.raw`Z=30/15=2`], String.raw`2`],
    mistake: "N(m,σ²)의 두 번째 값은 표준편차가 아니라 분산입니다. 표준화할 때는 그 제곱근인 σ로 나눕니다.",
    check: [String.raw`X\sim N(50,10^2)\text{에서 }X=40\text{의 표준화 값}`, String.raw`-1`, "(40-50)/10=-1이므로 평균보다 한 표준편차 아래입니다."],
    practice: [[String.raw`X\sim N(20,4^2)\text{일 때 }P(X\le20)`, String.raw`\frac12`, "정규분포는 평균 20을 중심으로 대칭이므로 왼쪽 확률은 1/2입니다."], [String.raw`Z\sim N(0,1),\ P(0\le Z\le1)=0.3413\text{일 때 }P(-1\le Z\le1)`, String.raw`0.6826`, "표준정규분포의 대칭성으로 양쪽 구간 확률은 0.3413의 두 배입니다."]],
  }),
  makeConcept({
    id: "statistics-sampling-estimation", order: 4, title: "표본평균과 모평균의 추정", question: "일부 표본으로 전체 집단의 평균을 어느 범위까지 추정할까?",
    core: "표본평균의 평균은 모평균이고 표준편차는 모표준편차를 √n으로 나눈 값이며, 이를 이용해 모평균의 신뢰구간을 만듭니다.",
    intuition: "표본의 크기가 커질수록 우연한 흔들림이 서로 상쇄되어 표본평균이 모평균 가까이에 모입니다. 그래서 오차의 크기가 1/√n에 비례해 줄어듭니다.",
    formulas: [String.raw`E(\bar X)=m,\quad \sigma(\bar X)=\frac{\sigma}{\sqrt n}`, String.raw`\begin{gathered}\bar x-1.96\frac{\sigma}{\sqrt n}\le m\\m\le\bar x+1.96\frac{\sigma}{\sqrt n}\quad(95\%)\end{gathered}`],
    example: [String.raw`\begin{gathered}\bar x=100,\quad \sigma=10\\n=100\text{일 때 }95\%\text{ 신뢰구간}\end{gathered}`, [String.raw`\text{표준오차는 }10/\sqrt{100}=1`, String.raw`100\pm1.96`], String.raw`98.04\le m\le101.96`],
    mistake: "표준오차를 σ/n으로 계산하지 않습니다. 표본 크기의 제곱근 √n으로 나눕니다.",
    check: [String.raw`\sigma=12,\ n=36\text{일 때 표본평균의 표준편차}`, String.raw`2`, "표준오차는 12/√36=12/6=2입니다."],
    practice: [[String.raw`\sigma=15,\ n=25\text{일 때 표본평균의 표준편차}`, String.raw`3`, "모표준편차 15를 √25=5로 나누면 3입니다."], [String.raw`\text{표본 크기를 4배로 하면 표준오차는 몇 배가 되는가?}`, String.raw`\frac12\text{배}`, "표준오차는 1/√n에 비례하므로 n이 4배이면 절반이 됩니다."]],
  }),
];

export const PROBABILITY_STATISTICS_CONCEPTS_BY_UNIT = {
  "probability-counting": PROBABILITY_COUNTING_CONCEPTS,
  probability: PROBABILITY_PROBABILITY_CONCEPTS,
  statistics: PROBABILITY_STATISTICS_CONCEPTS,
};

export const GEOMETRY_CONIC_CONCEPTS = [
  makeConcept({
    id: "geometry-parabola", order: 1, title: "포물선", question: "한 점과 한 직선까지의 거리가 같은 점들은 어떤 곡선을 만들까?",
    core: "초점과 준선까지의 거리가 같은 점의 자취가 포물선이며, 표준형에서 초점과 준선을 바로 읽을 수 있습니다.",
    intuition: "곡선 위 어느 점에서도 초점까지의 거리와 준선에 내린 수선의 길이가 같습니다. 이 거리 조건을 좌표로 쓰면 포물선의 방정식이 됩니다.",
    formulas: [String.raw`y^2=4px:\ F(p,0),\ x=-p`, String.raw`x^2=4py:\ F(0,p),\ y=-p`],
    example: [String.raw`y^2=8x\text{의 초점과 준선}`, [String.raw`4p=8\text{이므로 }p=2`, String.raw`F(2,0),\ x=-2`], String.raw`F(2,0),\ x=-2`],
    mistake: "y²=4px는 x축 방향으로 열린 포물선입니다. 제곱된 변수와 열리는 방향을 반대로 읽지 않습니다.",
    check: [String.raw`x^2=12y\text{의 초점}`, String.raw`(0,3)`, "4p=12이므로 p=3이고 초점은 y축 위 (0,3)입니다."],
    practice: [[String.raw`y^2=-4x\text{의 준선}`, String.raw`x=1`, "4p=-4에서 p=-1이고 준선은 x=-p=1입니다."], [String.raw`\text{초점이 }(0,2),\text{ 준선이 }y=-2\text{인 포물선}`, String.raw`x^2=8y`, "p=2인 위로 열린 포물선이므로 x²=4py=8y입니다."]],
  }),
  makeConcept({
    id: "geometry-ellipse", order: 2, title: "타원", question: "두 초점까지 거리의 합이 일정한 점들은 어떤 곡선을 만들까?",
    core: "두 초점까지 거리의 합이 2a로 일정한 점의 자취가 타원이며, 긴 반지름 a와 초점거리 c는 c²=a²-b²를 만족합니다.",
    intuition: "두 초점에 고정한 끈을 팽팽하게 당겨 그리면 거리의 합이 늘 일정해 타원이 됩니다. 긴 축이 어느 방향인지 먼저 확인합니다.",
    formulas: [String.raw`\frac{x^2}{a^2}+\frac{y^2}{b^2}=1\quad(a>b>0)`, String.raw`c^2=a^2-b^2,\quad F(\pm c,0)`],
    example: [String.raw`\frac{x^2}{25}+\frac{y^2}{9}=1\text{의 초점}`, [String.raw`a^2=25,\ b^2=9`, String.raw`c^2=25-9=16`], String.raw`(\pm4,0)`],
    mistake: "타원에서는 c²=a²-b²입니다. 분모가 큰 축의 방향에 초점이 놓입니다.",
    check: [String.raw`\frac{x^2}{16}+\frac{y^2}{7}=1\text{의 두 초점 사이 거리}`, String.raw`6`, "c²=16-7=9이므로 c=3이고 두 초점 사이 거리는 2c=6입니다."],
    practice: [[String.raw`\frac{x^2}{9}+\frac{y^2}{25}=1\text{의 초점}`, String.raw`(0,\pm4)`, "큰 분모가 y축에 있고 c²=25-9=16이므로 초점은 (0,±4)입니다."], [String.raw`a=5,\ c=3\text{인 타원의 }b^2`, String.raw`16`, "타원의 관계 c²=a²-b²에서 b²=25-9=16입니다."]],
  }),
  makeConcept({
    id: "geometry-hyperbola", order: 3, title: "쌍곡선", question: "두 초점까지 거리의 차가 일정한 점들은 어떤 곡선을 만들까?",
    core: "두 초점까지 거리의 차의 절댓값이 2a인 점의 자취가 쌍곡선이며, c²=a²+b²를 만족합니다.",
    intuition: "타원이 거리의 합을 고정한다면 쌍곡선은 거리의 차를 고정합니다. 곡선은 두 갈래로 나뉘고 멀리 갈수록 점근선에 가까워집니다.",
    formulas: [String.raw`\frac{x^2}{a^2}-\frac{y^2}{b^2}=1`, String.raw`c^2=a^2+b^2,\quad F(\pm c,0)`, String.raw`y=\pm\frac ba x`],
    example: [String.raw`\frac{x^2}{9}-\frac{y^2}{16}=1\text{의 초점}`, [String.raw`c^2=9+16=25`, String.raw`c=5`], String.raw`(\pm5,0)`],
    mistake: "쌍곡선에서는 c²=a²+b²입니다. 타원의 뺄셈 관계와 섞지 않습니다.",
    check: [String.raw`\frac{x^2}{4}-\frac{y^2}{9}=1\text{의 점근선}`, String.raw`y=\pm\frac32x`, "점근선의 기울기는 ±b/a이고 a=2, b=3이므로 ±3/2입니다."],
    practice: [[String.raw`\frac{y^2}{16}-\frac{x^2}{9}=1\text{의 초점}`, String.raw`(0,\pm5)`, "c²=16+9=25이고 양의 항이 y²이므로 초점은 y축 위에 있습니다."], [String.raw`a=3,\ b=4\text{인 쌍곡선의 두 초점 사이 거리}`, String.raw`10`, "c=√(3²+4²)=5이므로 두 초점 사이 거리는 2c=10입니다."]],
  }),
  makeConcept({
    id: "geometry-conic-tangents", order: 4, title: "이차곡선의 접선", question: "이차곡선 위 한 점에서의 접선은 어떻게 나타낼까?",
    core: "표준형의 곡선 위 점 좌표를 접선 공식에 대입하며, 그 점이 곡선 위에 있는지 먼저 확인합니다.",
    intuition: "접선 공식은 곡선 방정식의 제곱항 하나를 접점 좌표와 현재 좌표의 곱으로 바꾼 모양입니다. 타원과 쌍곡선의 부호는 원래 식을 그대로 유지합니다.",
    formulas: [String.raw`y^2=4px:\ yy_1=2p(x+x_1)`, String.raw`\frac{xx_1}{a^2}+\frac{yy_1}{b^2}=1`, String.raw`\frac{xx_1}{a^2}-\frac{yy_1}{b^2}=1`],
    example: [String.raw`\begin{gathered}\frac{x^2}{9}+\frac{y^2}{4}=1\\(0,2)\text{에서의 접선}\end{gathered}`, [String.raw`\frac{x\cdot0}{9}+\frac{y\cdot2}{4}=1`, String.raw`y=2`], String.raw`y=2`],
    mistake: "접선 공식에 곡선 위가 아닌 점을 그대로 넣지 않습니다. 주어진 점이 방정식을 만족하는지 먼저 대입해 확인합니다.",
    check: [String.raw`y^2=8x\text{ 위 }(2,4)\text{에서 접선}`, String.raw`y=x+2`, "p=2이므로 4y=4(x+2), 이를 정리하면 y=x+2입니다."],
    practice: [[String.raw`\frac{x^2}{4}+\frac{y^2}{9}=1\text{ 위 }(2,0)\text{에서 접선}`, String.raw`x=2`, "접선 공식에 (2,0)을 넣으면 2x/4=1이므로 x=2입니다."], [String.raw`\frac{x^2}{9}-\frac{y^2}{16}=1\text{ 위 }(3,0)\text{에서 접선}`, String.raw`x=3`, "쌍곡선 접선 공식에 (3,0)을 넣으면 3x/9=1입니다."]],
  }),
];

export const GEOMETRY_VECTOR_CONCEPTS = [
  makeConcept({
    id: "geometry-vector-operations", order: 1, title: "벡터의 뜻과 연산", question: "크기와 방향을 함께 가진 양은 어떻게 더하고 뺄까?",
    core: "벡터는 크기와 방향을 가지며, 삼각형법이나 평행사변형법으로 더하고 실수를 곱해 크기와 방향을 바꿉니다.",
    intuition: "한 이동 뒤에 다른 이동을 이어 붙인 전체 이동이 벡터의 합입니다. 뺄셈은 반대 방향의 벡터를 더하는 것으로 생각합니다.",
    formulas: [String.raw`\vec a+\vec b`, String.raw`\vec a-\vec b=\vec a+(-\vec b)`, String.raw`|k\vec a|=|k||\vec a|`],
    example: [String.raw`\vec a=(2,1),\ \vec b=(-1,3)\text{일 때 }\vec a+\vec b`, [String.raw`같은 위치의 성분끼리 더합니다.`, String.raw`(2-1,1+3)=(1,4)`], String.raw`(1,4)`],
    mistake: "벡터의 크기를 더한 값이 합벡터의 크기와 항상 같지는 않습니다. 방향이 같을 때만 크기가 그대로 더해집니다.",
    check: [String.raw`\vec a=(3,-2)\text{일 때 }-2\vec a`, String.raw`(-6,4)`, "각 성분에 -2를 곱하면 방향이 반대가 되고 크기는 두 배가 됩니다."],
    practice: [[String.raw`(1,5)-(3,2)`, String.raw`(-2,3)`, "같은 위치의 성분끼리 빼면 (1-3,5-2)=(-2,3)입니다."], [String.raw`\vec a\ne\vec0,\ k\vec a=\vec0\text{일 때 }k`, String.raw`0`, "영벡터가 아닌 벡터에 실수를 곱해 영벡터가 되려면 실수가 0이어야 합니다."]],
  }),
  makeConcept({
    id: "geometry-components-inner-product", order: 2, title: "벡터의 성분과 내적", question: "두 벡터가 이루는 각과 수직 여부를 좌표로 어떻게 판단할까?",
    core: "내적은 대응 성분의 곱의 합이며, 두 벡터의 크기와 끼인각의 코사인을 곱한 값과 같습니다.",
    intuition: "내적은 한 벡터가 다른 벡터 방향으로 얼마나 뻗어 있는지를 재는 값입니다. 서로 수직이면 그 방향 성분이 없어 내적이 0입니다.",
    formulas: [String.raw`\vec a\cdot\vec b=a_1b_1+a_2b_2`, String.raw`\vec a\cdot\vec b=|\vec a||\vec b|\cos\theta`, String.raw`\vec a\perp\vec b\iff\vec a\cdot\vec b=0`],
    example: [String.raw`\vec a=(1,2),\ \vec b=(3,-1)\text{의 내적}`, [String.raw`대응 성분을 곱해 더합니다.`, String.raw`1\cdot3+2\cdot(-1)=1`], String.raw`1`],
    mistake: "내적의 결과는 벡터가 아니라 하나의 수입니다. 성분끼리 곱한 결과를 벡터로 쓰지 않습니다.",
    check: [String.raw`(2,1)\text{과 }(1,-2)\text{는 수직인가?}`, String.raw`\text{수직이다}`, "내적 2×1+1×(-2)=0이므로 두 벡터는 수직입니다."],
    practice: [[String.raw`|(3,4)|`, String.raw`5`, "벡터의 크기는 √(3²+4²)=5입니다."], [String.raw`|\vec a|=2,\ |\vec b|=3,\ \theta=60^\circ\text{일 때 }\vec a\cdot\vec b`, String.raw`3`, "2×3×cos60°=6×1/2=3입니다."]],
  }),
  makeConcept({
    id: "geometry-position-vectors", order: 3, title: "위치벡터와 선분의 내분", question: "점의 위치와 선분을 나누는 점을 벡터로 어떻게 나타낼까?",
    core: "원점에서 한 점으로 향하는 위치벡터로 점을 나타내며, 선분 AB를 m:n으로 내분하는 점은 양 끝 위치벡터의 가중평균입니다.",
    intuition: "내분점은 두 끝점 사이에서 더 가까운 점의 반대쪽 비율을 가중치로 받습니다. 중점은 두 위치벡터의 단순 평균입니다.",
    formulas: [String.raw`\overrightarrow{AB}=\vec b-\vec a`, String.raw`\vec p=\frac{n\vec a+m\vec b}{m+n}\quad(AP:PB=m:n)`, String.raw`\vec m=\frac{\vec a+\vec b}{2}`],
    example: [String.raw`A(0,0),\ B(6,3),\ AP:PB=1:2\text{인 }P`, [String.raw`P=\frac{2A+1B}{3}`, String.raw`P=(2,1)`], String.raw`(2,1)`],
    mistake: "내분비 m:n을 A와 B에 같은 순서로 곱하지 않습니다. A에는 반대쪽 비율 n, B에는 m을 곱합니다.",
    check: [String.raw`A(1,2),\ B(5,6)\text{의 중점}`, String.raw`(3,4)`, "각 좌표의 평균을 구하면 ((1+5)/2,(2+6)/2)=(3,4)입니다."],
    practice: [[String.raw`A(2,-1),\ B(8,5),\ AP:PB=2:1\text{인 }P`, String.raw`(6,3)`, "P=(A+2B)/3=((2+16)/3,(-1+10)/3)=(6,3)입니다."], [String.raw`\vec a=(1,3),\ \vec b=(4,-2)\text{일 때 }\overrightarrow{AB}`, String.raw`(3,-5)`, "끝점의 위치벡터에서 시작점의 위치벡터를 빼면 (3,-5)입니다."]],
  }),
  makeConcept({
    id: "geometry-vector-equations", order: 4, title: "직선과 원의 벡터방정식", question: "직선 위 점과 원 위 점의 조건을 벡터로 어떻게 표현할까?",
    core: "직선 위 점은 한 점에서 방향벡터의 실수배만큼 이동한 위치이고, 원 위 점은 중심까지의 거리가 일정합니다.",
    intuition: "직선은 출발점과 진행 방향만 정하면 되고, 원은 중심과 반지름만 정하면 됩니다. 벡터식은 이 기하 조건을 그대로 적은 식입니다.",
    formulas: [String.raw`\vec p=\vec a+t\vec d`, String.raw`|\vec p-\vec c|=r`, String.raw`(\vec p-\vec a)\cdot\vec n=0`],
    example: [String.raw`\begin{gathered}A(1,2)\text{를 지나고}\\\text{방향벡터가 }(2,-1)\text{인 직선}\end{gathered}`, [String.raw`\vec p=\vec a+t\vec d`, String.raw`(x,y)=(1,2)+t(2,-1)`], String.raw`(x,y)=(1+2t,2-t)`],
    mistake: "직선의 방향벡터와 법선벡터를 혼동하지 않습니다. 법선벡터는 직선의 진행 방향과 수직입니다.",
    check: [String.raw`\text{중심 }(2,-1),\text{ 반지름 }3\text{인 원의 방정식}`, String.raw`(x-2)^2+(y+1)^2=9`, "중심까지 거리의 제곱이 반지름의 제곱 9와 같다는 식입니다."],
    practice: [[String.raw`(0,1)\text{을 지나고 방향벡터 }(1,2)\text{인 직선 위 }t=3\text{인 점}`, String.raw`(3,7)`, "(0,1)+3(1,2)=(3,7)입니다."], [String.raw`\vec p=(x,y),\ \vec a=(1,0),\ |\vec p-\vec a|=2\text{의 좌표 방정식}`, String.raw`(x-1)^2+y^2=4`, "점 (x,y)와 중심 (1,0)의 거리 제곱이 2²과 같습니다."]],
  }),
];

export const GEOMETRY_SPACE_CONCEPTS = [
  makeConcept({
    id: "geometry-space-relationships", order: 1, title: "공간에서의 위치 관계", question: "공간의 두 직선과 직선·평면은 어떤 관계를 가질까?",
    core: "공간의 두 직선은 만나거나 평행하거나 꼬인 위치에 있고, 직선과 평면은 포함·한 점에서 만남·평행 중 하나입니다.",
    intuition: "평면에서는 평행하지 않은 두 직선이 만나지만 공간에서는 서로 다른 높이로 비껴가는 꼬인 위치가 생깁니다. 같은 평면 위에 놓일 수 있는지가 기준입니다.",
    formulas: [String.raw`l\parallel m`, String.raw`l\perp\alpha`, String.raw`\alpha\parallel\beta`],
    example: [String.raw`\text{정육면체 }ABCD-EFGH\text{에서 }AB\text{와 }CG\text{의 위치 관계}`, [String.raw`AB\text{는 아래 면의 가로 모서리, }CG\text{는 세로 모서리입니다.}`, String.raw`서로 만나지 않고 평행하지 않으며 한 평면에 놓이지 않습니다.`], String.raw`\text{꼬인 위치}`],
    mistake: "공간에서 만나지 않는 두 직선을 모두 평행이라 하지 않습니다. 같은 평면 위에 놓이지 않으면 꼬인 위치입니다.",
    check: [String.raw`\text{한 직선이 평면 위 서로 만나는 두 직선에 모두 수직이면 그 평면과의 관계}`, String.raw`\text{수직}`, "평면 위에서 만나는 두 직선 모두에 수직인 직선은 그 평면에 수직입니다."],
    practice: [[String.raw`\text{서로 다른 두 평면이 한 직선에 모두 수직일 때 두 평면의 관계}`, String.raw`\text{평행}`, "같은 방향의 직선에 수직인 서로 다른 두 평면은 서로 평행합니다."], [String.raw`\text{평면 밖 한 점에서 그 평면에 내린 수선은 몇 개인가?}`, String.raw`1\text{개}`, "한 점에서 한 평면에 내릴 수 있는 수선은 유일하게 하나입니다."]],
  }),
  makeConcept({
    id: "geometry-orthogonal-projection", order: 2, title: "삼수선과 정사영", question: "공간의 선분을 평면에 비춘 길이와 넓이는 어떻게 구할까?",
    core: "선분의 정사영 길이는 원래 길이에 평면과 이루는 각의 코사인을 곱하고, 도형의 정사영 넓이도 같은 방식으로 구합니다.",
    intuition: "빛을 평면에 수직으로 비추어 생긴 그림자가 정사영입니다. 기울어질수록 그림자가 짧아지고, 그 줄어드는 비율이 cosθ입니다.",
    formulas: [String.raw`l'=l\cos\theta`, String.raw`S'=S\cos\theta`],
    example: [String.raw`\text{길이 10인 선분이 평면과 }60^\circ\text{를 이룰 때 정사영 길이}`, [String.raw`l'=l\cos\theta`, String.raw`10\cos60^\circ=5`], String.raw`5`],
    mistake: "직선과 평면의 각은 직선과 그 정사영이 이루는 예각입니다. 평면의 법선과 이루는 각과는 여각 관계입니다.",
    check: [String.raw`\text{넓이 12인 도형의 평면과의 각이 }60^\circ\text{일 때 정사영 넓이}`, String.raw`6`, "정사영 넓이는 12×cos60°=6입니다."],
    practice: [[String.raw`\text{길이 8인 선분이 평면과 }30^\circ\text{를 이룰 때 정사영 길이}`, String.raw`4\sqrt3`, "8×cos30°=8×√3/2=4√3입니다."], [String.raw`\text{정사영 넓이가 10이고 두 평면의 각이 }60^\circ\text{일 때 원래 넓이}`, String.raw`20`, "10=S×cos60°=S/2이므로 원래 넓이는 20입니다."]],
  }),
  makeConcept({
    id: "geometry-space-coordinates", order: 3, title: "공간좌표와 구", question: "3차원에서 두 점의 거리와 구의 방정식은 어떻게 나타낼까?",
    core: "공간의 거리는 세 좌표 차의 제곱합의 제곱근이고, 구는 중심에서 같은 거리 r인 점들의 집합입니다.",
    intuition: "평면의 거리 공식에 높이 방향 z의 차를 하나 더한 것입니다. 구의 방정식도 중심까지의 거리 제곱이 r²이라는 조건 그대로입니다.",
    formulas: [String.raw`AB=\sqrt{(x_2-x_1)^2+(y_2-y_1)^2+(z_2-z_1)^2}`, String.raw`(x-a)^2+(y-b)^2+(z-c)^2=r^2`],
    example: [String.raw`A(1,2,3),\ B(4,6,3)\text{의 거리}`, [String.raw`\text{좌표 차는 }(3,4,0)`, String.raw`AB=\sqrt{3^2+4^2}=5`], String.raw`5`],
    mistake: "공간좌표에서 z좌표의 차를 빠뜨리지 않습니다. 구의 오른쪽에는 반지름이 아니라 반지름의 제곱이 옵니다.",
    check: [String.raw`\text{중심 }(1,-2,3),\text{ 반지름 }4\text{인 구의 방정식}`, String.raw`(x-1)^2+(y+2)^2+(z-3)^2=16`, "중심 좌표의 부호를 반대로 넣고 오른쪽에 반지름의 제곱 16을 씁니다."],
    practice: [[String.raw`O(0,0,0),\ P(2,-3,6)\text{의 거리}`, String.raw`7`, "√(2²+(-3)²+6²)=√49=7입니다."], [String.raw`x^2+y^2+z^2-4x+6y-2z=2\text{인 구의 중심}`, String.raw`(2,-3,1)`, "각 변수별로 완전제곱하면 중심 좌표는 계수 절반의 반대 부호입니다."]],
  }),
  makeConcept({
    id: "geometry-space-distance-angle", order: 4, title: "공간의 거리와 각", question: "좌표와 벡터로 공간의 수직·각·거리를 어떻게 계산할까?",
    core: "공간벡터의 내적으로 두 방향의 각을 구하고, 점과 평면 사이 거리는 점에서 평면에 내린 수선의 길이로 계산합니다.",
    intuition: "3차원에서도 내적의 원리는 평면과 같습니다. 평면 ax+by+cz+d=0의 법선벡터가 (a,b,c)이므로 점에서 평면까지의 거리를 한 방향 성분으로 잴 수 있습니다.",
    formulas: [String.raw`\vec a\cdot\vec b=a_1b_1+a_2b_2+a_3b_3`, String.raw`\cos\theta=\frac{\vec a\cdot\vec b}{|\vec a||\vec b|}`, String.raw`d=\frac{|ax_0+by_0+cz_0+d|}{\sqrt{a^2+b^2+c^2}}`],
    example: [String.raw`\begin{gathered}P(1,2,3)\text{과 평면 }z=0\\\text{사이의 거리}\end{gathered}`, [String.raw`평면의 법선 방향은 z축입니다.`, String.raw`P\text{의 z좌표 절댓값은 }3`], String.raw`3`],
    mistake: "직선과 평면의 각을 구할 때 방향벡터와 법선벡터의 각을 그대로 쓰지 않습니다. 두 각은 서로 여각입니다.",
    check: [String.raw`(1,0,1)\text{과 }(1,0,-1)\text{이 이루는 각}`, String.raw`90^\circ`, "내적이 1-1=0이므로 두 벡터는 서로 수직입니다."],
    practice: [[String.raw`P(1,2,3)\text{과 평면 }x=0\text{ 사이 거리}`, String.raw`1`, "점에서 yz평면까지의 거리는 x좌표의 절댓값 1입니다."], [String.raw`P(1,1,1)\text{과 평면 }x+y+z=0\text{ 사이 거리}`, String.raw`\sqrt3`, "거리 공식으로 |1+1+1|/√3=3/√3=√3입니다."]],
  }),
];

export const GEOMETRY_CONCEPTS_BY_UNIT = {
  "geometry-conics": GEOMETRY_CONIC_CONCEPTS,
  "geometry-vectors": GEOMETRY_VECTOR_CONCEPTS,
  "geometry-space": GEOMETRY_SPACE_CONCEPTS,
};
