const LOCKED_CATALOG_BASE = "/eng-math/practice?subject=math&mode=catalog";

export const CALCULUS_QUESTION_TAGS = [
  {
    conceptId: "convergence-divergence",
    examKey: "2022_06",
    examLabel: "2022학년도 6월 모의평가",
    questionNumber: 23,
    sourceConcept: "수열의 극한",
    role: "기본 적용",
    connection: "수열식의 모양을 바꾼 뒤 실제로 가까워지는 값을 판단합니다.",
  },
  {
    conceptId: "convergence-divergence",
    examKey: "2026_csat",
    examLabel: "2026학년도 수능",
    questionNumber: 25,
    sourceConcept: "수열의 극한",
    role: "수렴 판단",
    connection: "주어진 범위로 수열을 끼워 수렴값을 확정하는 문항입니다.",
  },
  {
    conceptId: "limit-laws",
    examKey: "2023_09",
    examLabel: "2023학년도 9월 모의평가",
    questionNumber: 25,
    sourceConcept: "극한의 사칙연산",
    role: "조건 연결",
    connection: "두 극한 조건을 차례로 연결해 수열과 목표 극한값을 구합니다.",
  },
  {
    conceptId: "limit-laws",
    examKey: "2025_csat",
    examLabel: "2025학년도 수능",
    questionNumber: 25,
    sourceConcept: "수열의 극한",
    role: "식 변형",
    connection: "조건에서 필요한 극한을 먼저 얻고 무리식을 변형해 계산합니다.",
  },
  {
    conceptId: "geometric-sequence-limit",
    examKey: "2024_09",
    examLabel: "2024학년도 9월 모의평가",
    questionNumber: 29,
    sourceConcept: "등비수열의 극한",
    role: "공비 판단",
    connection: "등비수열의 공비에 따라 어떤 항이 전체 크기를 결정하는지 비교합니다.",
  },
  {
    conceptId: "geometric-sequence-limit",
    examKey: "2025_09",
    examLabel: "2025학년도 9월 모의평가",
    questionNumber: 25,
    sourceConcept: "등비수열",
    role: "공비 결정",
    connection: "극한이 유한한 양수가 되도록 등비수열의 공비를 결정합니다.",
  },
  {
    conceptId: "infinite-series",
    examKey: "2023_06",
    examLabel: "2023학년도 6월 모의평가",
    questionNumber: 27,
    sourceConcept: "급수 수렴의 필요조건",
    role: "수렴 조건",
    connection: "급수가 수렴하려면 일반항이 0으로 가야 한다는 조건을 먼저 씁니다.",
  },
  {
    conceptId: "infinite-series",
    examKey: "2025_06",
    examLabel: "2025학년도 6월 모의평가",
    questionNumber: 25,
    sourceConcept: "급수 수렴의 필요조건",
    role: "필요조건",
    connection: "급수의 수렴 조건을 수열의 극한으로 바꾸어 다음 계산을 시작합니다.",
  },
  {
    conceptId: "geometric-series",
    examKey: "2024_06",
    examLabel: "2024학년도 6월 모의평가",
    questionNumber: 30,
    sourceConcept: "무한등비급수",
    role: "공비와 합",
    connection: "조건으로 첫째항과 공비를 정한 뒤 무한등비급수의 합을 계산합니다.",
  },
  {
    conceptId: "geometric-series",
    examKey: "2025_csat",
    examLabel: "2025학년도 수능",
    questionNumber: 29,
    sourceConcept: "등비급수",
    role: "조건 해석",
    connection: "두 급수 조건을 이용해 첫째항과 음의 공비를 함께 결정합니다.",
  },
  {
    conceptId: "geometric-series-applications",
    examKey: "2022_06",
    examLabel: "2022학년도 6월 모의평가",
    questionNumber: 26,
    sourceConcept: "무한등비급수",
    role: "도형 활용",
    connection: "반복되는 부채꼴의 길이비를 넓이비로 바꾸어 무한합을 만듭니다.",
  },
  {
    conceptId: "geometric-series-applications",
    examKey: "2023_09",
    examLabel: "2023학년도 9월 모의평가",
    questionNumber: 27,
    sourceConcept: "등비급수",
    role: "도형 활용",
    connection: "닮은 도형의 길이비에서 넓이비를 구해 색칠한 넓이를 누적합니다.",
  },
  {
    conceptId: "exponential-log-derivatives",
    examKey: "2023_09",
    examLabel: "2023학년도 9월 모의평가",
    questionNumber: 23,
    sourceConcept: "지수함수의 미분",
    role: "미분계수 연결",
    connection: "지수함수의 미분계수 극한을 자연로그 식으로 바꾸어 계산합니다.",
  },
  {
    conceptId: "exponential-log-derivatives",
    examKey: "2024_06",
    examLabel: "2024학년도 6월 모의평가",
    questionNumber: 25,
    sourceConcept: "지수함수의 미분",
    role: "기본 극한 적용",
    connection: "지수함수의 미분계수와 같은 모양을 찾아 극한 조건을 해석합니다.",
  },
  {
    conceptId: "trigonometric-derivatives",
    examKey: "2022_06",
    examLabel: "2022학년도 6월 모의평가",
    questionNumber: 24,
    sourceConcept: "삼각함수의 미분",
    role: "매개변수와 결합",
    connection: "좌표를 매개변수로 미분하는 과정에서 삼각함수의 도함수를 사용합니다.",
  },
  {
    conceptId: "trigonometric-derivatives",
    examKey: "2024_09",
    examLabel: "2024학년도 9월 모의평가",
    questionNumber: 24,
    sourceConcept: "삼각함수의 미분",
    role: "기울기 계산",
    connection: "삼각함수가 포함된 두 좌표를 미분해 곡선의 기울기를 계산합니다.",
  },
  {
    conceptId: "product-quotient-derivatives",
    examKey: "2023_06",
    examLabel: "2023학년도 6월 모의평가",
    questionNumber: 24,
    sourceConcept: "곱의 미분법",
    role: "곱의 미분",
    connection: "두 식이 곱으로 연결된 관계를 미분해 접선의 기울기를 구합니다.",
  },
  {
    conceptId: "product-quotient-derivatives",
    examKey: "2024_06",
    examLabel: "2024학년도 6월 모의평가",
    questionNumber: 24,
    sourceConcept: "몫의 미분",
    role: "몫의 미분",
    connection: "매개변수로 주어진 좌표의 변화율을 구하는 과정에서 몫의 미분을 사용합니다.",
  },
  {
    conceptId: "chain-rule",
    examKey: "2025_06",
    examLabel: "2025학년도 6월 모의평가",
    questionNumber: 24,
    sourceConcept: "연쇄법칙",
    role: "안쪽 미분",
    connection: "삼각함수 안쪽의 식도 함께 변하므로 바깥 도함수에 안쪽의 변화율을 곱합니다.",
  },
  {
    conceptId: "chain-rule",
    examKey: "2025_09",
    examLabel: "2025학년도 9월 모의평가",
    questionNumber: 27,
    sourceConcept: "합성함수의 미분",
    role: "함수방정식",
    connection: "함수 안에 다시 함수가 들어간 항을 미분해 두 지점의 도함수 값을 연결합니다.",
  },
  {
    conceptId: "inverse-function-derivative",
    examKey: "2023_06",
    examLabel: "2023학년도 6월 모의평가",
    questionNumber: 25,
    sourceConcept: "역함수의 미분법",
    role: "대응점 찾기",
    connection: "역함수의 입력에 대응하는 원함수의 점을 먼저 찾고 그 점에서 기울기의 역수를 취합니다.",
  },
  {
    conceptId: "inverse-function-derivative",
    examKey: "2025_06",
    examLabel: "2025학년도 6월 모의평가",
    questionNumber: 28,
    sourceConcept: "역함수의 미분",
    role: "역함수 가지",
    connection: "조건에 맞는 역함수의 가지를 고른 뒤 원함수의 대응점에서 도함수의 역수를 사용합니다.",
  },
  {
    conceptId: "parametric-derivative",
    examKey: "2022_09",
    examLabel: "2022학년도 9월 모의평가",
    questionNumber: 25,
    sourceConcept: "매개변수로 나타낸 함수의 미분",
    role: "변화율의 비",
    connection: "x와 y를 각각 매개변수로 미분한 뒤 세로 변화율을 가로 변화율로 나눕니다.",
  },
  {
    conceptId: "parametric-derivative",
    examKey: "2026_csat",
    examLabel: "2026학년도 수능",
    questionNumber: 27,
    sourceConcept: "매개변수 미분",
    role: "교점의 기울기",
    connection: "직선과 만나는 점의 매개변수 값을 먼저 찾고 두 변화율의 비로 접선 기울기를 구합니다.",
  },
  {
    conceptId: "implicit-differentiation",
    examKey: "2024_06",
    examLabel: "2024학년도 6월 모의평가",
    questionNumber: 29,
    sourceConcept: "음함수 미분",
    role: "접선의 기울기",
    connection: "x와 y가 함께 들어 있는 곡선식을 미분해 두 점에서 접선의 기울기를 구합니다.",
  },
  {
    conceptId: "implicit-differentiation",
    examKey: "2024_09",
    examLabel: "2024학년도 9월 모의평가",
    questionNumber: 30,
    sourceConcept: "음함수 미분",
    role: "길이의 변화율",
    connection: "길이와 각의 관계식을 음함수 미분해 도형의 넓이가 변하는 속도를 계산합니다.",
  },
  {
    conceptId: "second-derivative",
    examKey: "2025_09",
    examLabel: "2025학년도 9월 모의평가",
    questionNumber: 11,
    track: "common",
    trackLabel: "공통",
    sourceConcept: "위치·속도·가속도",
    role: "두 번 미분",
    connection: "두 위치함수를 두 번 미분해 같은 시각에서 두 점의 가속도 차를 비교합니다.",
  },
  {
    conceptId: "second-derivative",
    examKey: "2025_csat",
    examLabel: "2025학년도 수능",
    questionNumber: 11,
    track: "common",
    trackLabel: "공통",
    sourceConcept: "가속도",
    role: "방향 전환과 가속도",
    connection: "속도의 부호가 바뀌는 시각을 찾고 속도를 다시 미분해 그때의 가속도를 구합니다.",
  },
  {
    conceptId: "tangent-normal-lines",
    examKey: "2022_06",
    examLabel: "2022학년도 6월 모의평가",
    questionNumber: 25,
    sourceConcept: "접선의 방정식",
    role: "접점과 기울기",
    connection: "원점을 지나도록 접점을 정하고 도함수로 두 접선의 기울기를 구합니다.",
  },
  {
    conceptId: "tangent-normal-lines",
    examKey: "2025_06",
    examLabel: "2025학년도 6월 모의평가",
    questionNumber: 27,
    sourceConcept: "접선과 법선",
    role: "법선의 절편",
    connection: "지수함수의 접선 기울기에서 음의 역수를 취해 법선을 세우고 절편을 구합니다.",
  },
  {
    conceptId: "increasing-decreasing-extrema",
    examKey: "2022_09",
    examLabel: "2022학년도 9월 모의평가",
    questionNumber: 5,
    track: "common",
    trackLabel: "공통",
    sourceConcept: "함수의 증가와 감소",
    role: "도함수 부호표",
    connection: "도함수를 인수분해하고 부호 변화를 읽어 극댓값과 극솟값을 구합니다.",
  },
  {
    conceptId: "increasing-decreasing-extrema",
    examKey: "2024_09",
    examLabel: "2024학년도 9월 모의평가",
    questionNumber: 6,
    track: "common",
    trackLabel: "공통",
    sourceConcept: "삼차함수의 극값",
    role: "극점에서 역추론",
    connection: "두 극점의 위치를 도함수의 두 근으로 바꾸어 도함수를 인수분해합니다.",
  },
  {
    conceptId: "antiderivative-basics",
    examKey: "2024_06",
    examLabel: "2024학년도 6월 모의평가",
    questionNumber: 17,
    track: "common",
    trackLabel: "공통",
    sourceConcept: "부정적분",
    role: "적분상수 결정",
    connection: "도함수를 항별로 적분하고 한 점의 함숫값으로 적분상수를 결정합니다.",
  },
  {
    conceptId: "antiderivative-basics",
    examKey: "2025_csat",
    examLabel: "2025학년도 수능",
    questionNumber: 17,
    track: "common",
    trackLabel: "공통",
    sourceConcept: "부정적분",
    role: "원함수 복원",
    connection: "주어진 도함수를 부정적분한 뒤 초기조건을 적용해 필요한 함숫값을 구합니다.",
  },
  {
    conceptId: "definite-integral-basics",
    examKey: "2025_09",
    examLabel: "2025학년도 9월 모의평가",
    questionNumber: 9,
    track: "common",
    trackLabel: "공통",
    sourceConcept: "정적분의 선형성",
    role: "같은 구간 합치기",
    connection: "같은 구간의 두 정적분을 하나로 합친 뒤 다항함수의 정적분을 계산합니다.",
  },
  {
    conceptId: "definite-integral-basics",
    examKey: "2025_csat",
    examLabel: "2025학년도 수능",
    questionNumber: 9,
    track: "common",
    trackLabel: "공통",
    sourceConcept: "정적분의 구간 가법성",
    role: "공통 구간 없애기",
    connection: "두 정적분의 겹치는 구간을 없애고 남은 구간을 하나의 정적분으로 정리합니다.",
  },
  {
    conceptId: "integral-defined-function",
    examKey: "2025_csat",
    examLabel: "2025학년도 수능",
    questionNumber: 7,
    track: "common",
    trackLabel: "공통",
    sourceConcept: "정적분으로 정의된 함수",
    role: "누적함수 복원",
    connection: "움직이는 끝점을 가진 정적분을 미분해 숨어 있는 함수 f(x)를 바로 드러냅니다.",
  },
  {
    conceptId: "integral-defined-function",
    examKey: "2026_csat",
    examLabel: "2026학년도 수능",
    questionNumber: 15,
    track: "common",
    trackLabel: "공통",
    sourceConcept: "정적분으로 정의된 함수",
    role: "누적함수의 극값",
    connection: "두 함수의 차를 누적한 함수를 미분해 도함수의 부호와 극값 조건을 판단합니다.",
  },
  {
    conceptId: "areas-with-integrals",
    examKey: "2024_09",
    examLabel: "2024학년도 9월 모의평가",
    questionNumber: 19,
    track: "common",
    trackLabel: "공통",
    sourceConcept: "두 곡선 사이의 넓이",
    role: "교점과 위아래 판단",
    connection: "두 곡선의 교점을 구하고 그 사이에서 위 함수에서 아래 함수를 빼 넓이를 계산합니다.",
  },
  {
    conceptId: "areas-with-integrals",
    examKey: "2026_csat",
    examLabel: "2026학년도 수능",
    questionNumber: 7,
    track: "common",
    trackLabel: "공통",
    sourceConcept: "곡선 사이의 넓이",
    role: "직선까지의 넓이",
    connection: "교점부터 주어진 직선까지 두 함수의 차를 정적분해 둘러싸인 넓이를 구합니다.",
  },
  {
    conceptId: "motion-with-integrals",
    examKey: "2022_09",
    examLabel: "2022학년도 9월 모의평가",
    questionNumber: 9,
    track: "common",
    trackLabel: "공통",
    sourceConcept: "정적분과 이동거리",
    role: "속도의 부호와 방향 전환",
    connection: "속도가 0이 되는 시각으로 방향 전환을 찾고, 음수인 구간의 적분값은 부호를 바꾸어 이동거리에 더합니다.",
  },
  {
    conceptId: "motion-with-integrals",
    examKey: "2023_06",
    examLabel: "2023학년도 6월 모의평가",
    questionNumber: 11,
    track: "common",
    trackLabel: "공통",
    sourceConcept: "정적분으로 구하는 이동거리",
    role: "구간별 이동거리",
    connection: "위치 조건으로 이동 시간을 정한 뒤 속도의 부호가 바뀌는 구간을 나누어 전체 이동거리를 구합니다.",
  },
  {
    conceptId: "substitution-integration",
    examKey: "2024_09",
    examLabel: "2024학년도 9월 모의평가",
    questionNumber: 25,
    sourceConcept: "치환적분",
    role: "안쪽 함수와 도함수 찾기",
    connection: "적분식에서 f(x)와 f′(x)의 짝을 찾아 f(x)를 새 변수로 보고 양 끝값을 대입합니다.",
  },
  {
    conceptId: "substitution-integration",
    examKey: "2026_csat",
    examLabel: "2026학년도 수능",
    questionNumber: 24,
    sourceConcept: "치환적분",
    role: "삼각함수 정리 후 치환",
    connection: "항등식으로 근호를 정리한 뒤 sin x를 새 변수로 두어 cos x dx를 함께 바꿉니다.",
  },
  {
    conceptId: "integration-by-parts",
    examKey: "2023_09",
    examLabel: "2023학년도 9월 모의평가",
    questionNumber: 24,
    sourceConcept: "부분적분",
    role: "삼각함수 정리 뒤 부분적분",
    connection: "여각 공식으로 x sin x 꼴을 만든 뒤 x를 미분할 함수로 골라 부분적분합니다.",
  },
  {
    conceptId: "integration-by-parts",
    examKey: "2026_csat",
    examLabel: "2026학년도 수능",
    questionNumber: 26,
    sourceConcept: "부분적분",
    role: "부피 적분의 로그항 정리",
    connection: "단면적으로 만든 적분에서 x ln x를 부분적분해 계산 가능한 식으로 바꿉니다.",
  },
  {
    conceptId: "volumes-with-integrals",
    examKey: "2023_09",
    examLabel: "2023학년도 9월 모의평가",
    questionNumber: 26,
    sourceConcept: "단면의 넓이",
    role: "한 변의 길이에서 단면적 만들기",
    connection: "곡선의 함수값을 정사각형의 한 변으로 읽고, 그 제곱을 단면적으로 만들어 적분합니다.",
  },
  {
    conceptId: "volumes-with-integrals",
    examKey: "2025_csat",
    examLabel: "2025학년도 수능",
    questionNumber: 26,
    sourceConcept: "단면의 넓이와 부피",
    role: "단면적을 부피로 누적하기",
    connection: "각 x에서 정사각형 단면의 넓이를 구한 뒤 주어진 구간 전체에 정적분해 부피를 구합니다.",
  },
].map((question) => {
  const track = question.track ?? "cal";
  return {
    ...question,
    track,
    trackLabel: question.trackLabel ?? "미적분",
    access: "locked",
    catalogPath: `${LOCKED_CATALOG_BASE}&exam=${question.examKey}&track=${track}`,
  };
});

export function getCalculusQuestionsForConcept(conceptId) {
  return CALCULUS_QUESTION_TAGS.filter(
    (question) => question.conceptId === conceptId,
  );
}
